security:
    password_hashers:
        App\Entity\User: 'auto'  # Specify the actual User entity for password hashing

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User  # Use your User entity
                property: email  # Use 'email' or another unique identifier field

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\AccessDeniedHandler
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 60
                path: /home
                always_remember_me: true
            access_denied_url: /access-denied


    access_control:
        # - { path: ^/dashboared, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
